name = input("What is your name:  ")
print("Hello", name)
age = input("How old are you? ")
print( age, "WOW!Me too")
location = input('Where are you from(country)?  ')
print(location, 'is a beautiful country:)')
how_long = input('how many years have you lived there?')
print('Not bad!')